# 此处密码,采用单密钥进行加密，加密结果使用定义的前后缀包裹
password: abc[dIzeBKUMf+LSuumi1xodNUxuE9vW6AxipDLas1rrygbqMhqn2oUGOrCYRRFG+zfx]

# 秘钥
jasypt:
  encryptor:
    # 密钥定义，不建议在此处
    # 建议-D参数注入
    # java -jar -Djasypt.encryptor.password=1123  springboot-jasypt-2.3.3.RELEASE.jar
    password: miyao
    property:
      prefix: "abc["
      suffix: "]"
