spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8087
  profiles:
    active: dev2
management:
  endpoints:
    web:
      exposure:
        include: '*'
